// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type MallocGCAllocEntry struct {
	Size        uint64
	GoroutineId uint64
}

// LoadMallocGC returns the embedded CollectionSpec for MallocGC.
func LoadMallocGC() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_MallocGCBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load MallocGC: %w", err)
	}

	return spec, err
}

// LoadMallocGCObjects loads MallocGC and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*MallocGCObjects
//	*MallocGCPrograms
//	*MallocGCMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadMallocGCObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadMallocGC()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// MallocGCSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MallocGCSpecs struct {
	MallocGCProgramSpecs
	MallocGCMapSpecs
}

// MallocGCSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MallocGCProgramSpecs struct {
	UprobeMallocgcEntry   *ebpf.ProgramSpec `ebpf:"uprobe_mallocgc_entry"`
	UretprobeMallocgcExit *ebpf.ProgramSpec `ebpf:"uretprobe_mallocgc_exit"`
}

// MallocGCMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MallocGCMapSpecs struct {
	AllocScratch *ebpf.MapSpec `ebpf:"alloc_scratch"`
	Events       *ebpf.MapSpec `ebpf:"events"`
}

// MallocGCObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadMallocGCObjects or ebpf.CollectionSpec.LoadAndAssign.
type MallocGCObjects struct {
	MallocGCPrograms
	MallocGCMaps
}

func (o *MallocGCObjects) Close() error {
	return _MallocGCClose(
		&o.MallocGCPrograms,
		&o.MallocGCMaps,
	)
}

// MallocGCMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadMallocGCObjects or ebpf.CollectionSpec.LoadAndAssign.
type MallocGCMaps struct {
	AllocScratch *ebpf.Map `ebpf:"alloc_scratch"`
	Events       *ebpf.Map `ebpf:"events"`
}

func (m *MallocGCMaps) Close() error {
	return _MallocGCClose(
		m.AllocScratch,
		m.Events,
	)
}

// MallocGCPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadMallocGCObjects or ebpf.CollectionSpec.LoadAndAssign.
type MallocGCPrograms struct {
	UprobeMallocgcEntry   *ebpf.Program `ebpf:"uprobe_mallocgc_entry"`
	UretprobeMallocgcExit *ebpf.Program `ebpf:"uretprobe_mallocgc_exit"`
}

func (p *MallocGCPrograms) Close() error {
	return _MallocGCClose(
		p.UprobeMallocgcEntry,
		p.UretprobeMallocgcExit,
	)
}

func _MallocGCClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed mallocgc_bpfel.o
var _MallocGCBytes []byte
