// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type SyscallsSyscallScratch struct {
	TimestampNs uint64
	Nr          uint32
	Pad         uint32
}

// LoadSyscalls returns the embedded CollectionSpec for Syscalls.
func LoadSyscalls() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SyscallsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Syscalls: %w", err)
	}

	return spec, err
}

// LoadSyscallsObjects loads Syscalls and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*SyscallsObjects
//	*SyscallsPrograms
//	*SyscallsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadSyscallsObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadSyscalls()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// SyscallsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SyscallsSpecs struct {
	SyscallsProgramSpecs
	SyscallsMapSpecs
}

// SyscallsSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SyscallsProgramSpecs struct {
	TpSysEnter *ebpf.ProgramSpec `ebpf:"tp_sys_enter"`
	TpSysExit  *ebpf.ProgramSpec `ebpf:"tp_sys_exit"`
}

// SyscallsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SyscallsMapSpecs struct {
	SyscallEvents     *ebpf.MapSpec `ebpf:"syscall_events"`
	SyscallScratchMap *ebpf.MapSpec `ebpf:"syscall_scratch_map"`
	TargetPid         *ebpf.MapSpec `ebpf:"target_pid"`
}

// SyscallsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadSyscallsObjects or ebpf.CollectionSpec.LoadAndAssign.
type SyscallsObjects struct {
	SyscallsPrograms
	SyscallsMaps
}

func (o *SyscallsObjects) Close() error {
	return _SyscallsClose(
		&o.SyscallsPrograms,
		&o.SyscallsMaps,
	)
}

// SyscallsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadSyscallsObjects or ebpf.CollectionSpec.LoadAndAssign.
type SyscallsMaps struct {
	SyscallEvents     *ebpf.Map `ebpf:"syscall_events"`
	SyscallScratchMap *ebpf.Map `ebpf:"syscall_scratch_map"`
	TargetPid         *ebpf.Map `ebpf:"target_pid"`
}

func (m *SyscallsMaps) Close() error {
	return _SyscallsClose(
		m.SyscallEvents,
		m.SyscallScratchMap,
		m.TargetPid,
	)
}

// SyscallsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadSyscallsObjects or ebpf.CollectionSpec.LoadAndAssign.
type SyscallsPrograms struct {
	TpSysEnter *ebpf.Program `ebpf:"tp_sys_enter"`
	TpSysExit  *ebpf.Program `ebpf:"tp_sys_exit"`
}

func (p *SyscallsPrograms) Close() error {
	return _SyscallsClose(
		p.TpSysEnter,
		p.TpSysExit,
	)
}

func _SyscallsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed syscalls_bpfel.o
var _SyscallsBytes []byte
